theme: jekyll-theme-hacker
name: Nekotov blog
description: Red teamer
avatar: ../images/logo.png
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: Nekotov
  instagram:
  linkedin:
  pinterest:
  rss: 
  twitter: sudo_sudo_su
  stackoverflow: 
  youtube: 
  googleplus:


disqus:
google_analytics:
url:
baseurl: ""
permalink: /:title/
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
sass:
  style: :expanded # You might prefer to minify using :compressed
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-gist

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

